# Generated by Django 3.0.7 on 2020-06-08 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspost', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='lolCategory',
            new_name='subcategory',
        ),
    ]
