# Generated by Django 3.0.7 on 2020-06-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspost', '0004_auto_20200608_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='thumbnail',
            field=models.ImageField(default='thumbnails/download.jpeg', upload_to='thumbnails/'),
        ),
    ]
