# Generated by Django 3.0.7 on 2020-06-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspost', '0005_auto_20200608_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='ChiefStory',
            field=models.BooleanField(default=False),
        ),
    ]
