# Generated by Django 3.0.7 on 2020-06-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspost', '0006_articles_chiefstory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ('-publish',)},
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='ChiefStory',
            new_name='BreakingNews',
        ),
        migrations.AddField(
            model_name='articles',
            name='ChiefNews',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articles',
            name='PopularNews',
            field=models.BooleanField(default=False),
        ),
    ]
