# Generated by Django 3.0.7 on 2020-06-08 18:43

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('newspost', '0007_auto_20200608_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='BiharNews',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='articles',
            name='subcategory',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='category', chained_model_field='category', null=True, on_delete=django.db.models.deletion.CASCADE, to='newspost.SubCategory'),
        ),
    ]
