# Generated by Django 3.0.7 on 2020-06-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspost', '0008_auto_20200609_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='advertisment')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('exclusiveVideo', models.BooleanField(default=False)),
            ],
        ),
    ]
