# Generated by Django 3.0.7 on 2020-06-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspost', '0009_advertisment_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisment',
            name='url',
            field=models.CharField(default='abc', max_length=1000),
            preserve_default=False,
        ),
    ]
