# Generated by Django 3.0.7 on 2020-06-09 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspost', '0010_advertisment_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='exclusiveVideo',
        ),
    ]
