# Generated by Django 3.0.7 on 2020-06-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspost', '0011_remove_video_exclusivevideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='exclusiveVideo',
            field=models.BooleanField(default=False),
        ),
    ]
