# Generated by Django 3.0.7 on 2020-06-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspost', '0013_articles_url_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='reporter/')),
                ('dob', models.DateField()),
                ('mob_number', models.CharField(max_length=10)),
                ('adhar_number', models.CharField(max_length=16)),
                ('qualification', models.CharField(max_length=80)),
                ('address', models.TextField()),
                ('isReporter', models.BooleanField(default=False)),
                ('designation', models.CharField(max_length=120)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=False)),
            ],
        ),
    ]
