# Generated by Django 3.0.7 on 2020-06-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspost', '0014_reporter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporter',
            name='designation',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
